const cheatCodeTeam = [{
    name: "MEWTWO",
    cry: "charizardcry.mp3",
    type: ["PSYCHIC"],
    weakness: ["DARK", "BUG"],
    resist: ["BUG", "GRASS", "BUG", "GRASS", "FAIRY", "FIRE", "FIGHTING", "GROUND", "STEEL",],
    img: "mewtwo.png",
    tinyPic: "mewtwo.gif",
    fainted: false,
    inCombat: false,
    poisoned: false,
    paralyzed: false,
    burned: false,
    frozen: 0,
    confused: 0,
    asleep: 0,
    hp: 353,
    totalHP: 353,
    level: "Lv:100",
    combatLvl: 100,
    attack: 281,
    specialAttack: 309,
    defense: 216,
    specialDefense: 216,
    speed: 296,
    moves: [{
        name: "PSYCHIC",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 90,
        accuracy: 1
    },
    {
        name: "PSYCHO CUT",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 35,
        maxPP: 35,
        power: 70,
        accuracy: 1,
    },
    {
        name: "CONFUSION",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 50,
        accuracy:1,
    },
    {
        name: "PSYSTRIKE",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 100,
        accuracy: 1,
    }]
},
{
    name: "ARTICUNO",
    type: ["ICE", "FLYING"],
    cry: "blastoisecry.mp3",
    img: "articuno.png",
    tinyPic: "articuno.gif",
    weakness: ["ROCK", "FIRE",],
    resist: ["ICE", "STEEL", "WATER"],
    fainted: false,
    poisoned: false,
    inCombat: false,
    paralyzed: false,
    burned: false,
    frozen: 0,
    confused: 0,
    asleep: 0,
    hp: 321,
    totalHP: 321,
    level: "Lv:100",
    combatLvl: 100,
    attack: 226,
    specialAttack: 203,
    defense: 236,
    specialDefense: 286,
    speed: 206,
    moves: [{
        name: "ICE BEAM",
        type: "ICE",
        physical: false,
        special: true,
        status: false,
        pp: 15,
        maxPP: 15,
        power: 90,
        accuracy: 1
    },
    {
        name: "POWDER SNOW",
        type: "ICE",
        physical: false,
        special: true,
        status: false,
        pp: 15,
        maxPP: 15,
        power: 40,
        accuracy: 1,
    },
    {
        name: "HURRICANE",
        type: "FLYING",
        physical: true,
        special: false,
        status: false,
        pp: 10,
        maxPP: 10,
        power: 110,
        accuracy: 1,
    },
    {
        name: "BLIZZARD",
        type: "ICE",
        physical: false,
        special: true,
        status: false,
        loseTurn: false,
        pp: 15,
        maxPP: 15,
        power: 110,
        accuracy: 1,
    }]
},
{
    name: "ZAPDOS",
    type: ["ELECTRIC", "FLYING"],
    cry: "venusaurcry.mp3",
    weakness: ["ROCK", "GROUND"],
    resist: ["ELECTRIC", "FLYING"],
    img: "zapdos.png",
    tinyPic: "zapdos.gif",
    fainted: false,
    inCombat: false,
    poisoned: false,
    paralyzed: false,
    burned: false,
    frozen: 0,
    confused: 0,
    asleep: 0,
    hp: 321,
    totalHP: 321,
    level: "Lv:100",
    combatLvl: 100,
    attack: 237,
    specialAttack: 257,
    defense: 206,
    specialDefense: 216,
    speed: 236,
    moves: [{
        name: "ZAP CANNON",
        type: "ELECTRIC",
        physical: true,
        special: false,
        status: false,
        pp: 15,
        maxPP: 15,
        power: 120,
        accuracy: 8
    },
    {
        name: "THUNDER",
        type: "ELECTRIC",
        physical: true,
        special: false,
        status: false,
        pp: 15,
        maxPP: 15,
        power: 110,
        accuracy: 95
    },
    {
        name: "DISCHARGE",
        type: "ELECTRIC",
        physical: true,
        special: false,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 80,
        accuracy: 95
    },
    {
        name: "DRILL PECK",
        type: "FLYING",
        physical: true,
        special: false,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 80,
        accuracy: 1
    },]
},
{
    name: "MOLTRES",
    type: ["FIRE", "FLYING"],
    cry: "laprascry.mp3",
    weakness: ["ROCK", "WATER"],
    resist: ["FIRE", "FLYING", "GRASS"],
    img: "moltres.png",
    tinyPic: "moltres.gif",
    fainted: false,
    inCombat: false,
    poisoned: false,
    paralyzed: false,
    burned: false,
    frozen: 0,
    confused: 0,
    asleep: 0,
    hp: 321,
    totalHP: 321,
    level: "Lv:100",
    combatLvl: 100,
    attack: 259,
    specialAttack: 257,
    defense: 216,
    specialDefense: 206,
    speed: 216,
    moves: [{
        name: "BURN UP",
        type: "FIRE",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 140,
        accuracy: 1
    },
    {
        name: "FLAMETHROWER",
        type: "FIRE",
        physical: false,
        special: true,
        status: false,
        pp: 25,
        maxPP: 25,
        power: 80,
        accuracy: .75,
    },
    {
        name: "INCINERATE",
        type: "FIRE",
        physical: false,
        special: true,
        status: true,
        pp: 15,
        maxPP: 15,
        power: 95,
        accuracy: 1,
    },
    {
        name: "HEAT WAVE",
        type: "FIRE",
        physical: false,
        special: true,
        status: false,
        pp: 15,
        maxPP: 15,
        power: 90,
        accuracy: .75,
    }]
},
{
    name: "MEW",
    cry: "charizardcry.mp3",
    type: ["PSYCHIC"],
    weakness: ["DARK", "BUG"],
    resist: ["BUG", "GRASS", "BUG", "GRASS", "FAIRY", "FIRE", "FIGHTING", "GROUND", "STEEL",],
    img: "mew.png",
    tinyPic: "mew.gif",
    fainted: false,
    inCombat: false,
    poisoned: false,
    paralyzed: false,
    burned: false,
    frozen: 0,
    confused: 0,
    asleep: 0,
    hp: 353,
    totalHP: 353,
    level: "Lv:100",
    combatLvl: 100,
    attack: 281,
    specialAttack: 309,
    defense: 216,
    specialDefense: 216,
    speed: 296,
    moves: [{
        name: "PSYCHIC",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 90,
        accuracy: 1
    },
    {
        name: "PSYCHO CUT",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 35,
        maxPP: 35,
        power: 70,
        accuracy: 1,
    },
    {
        name: "CONFUSION",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 50,
        accuracy:1,
    },
    {
        name: "PSYSTRIKE",
        type: "PSYCHIC",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 100,
        accuracy: 1,
    }]
},
{
    name: "DRAGONITE",
    type: ["DRAGON", "FLYING"],
    cry: "alakazamcry.mp3",
    img: "dragonite.png",
    tinyPic: "dragonite.gif",
    weakness: ["ROCK", "DRAGON","IC"],
    resist: ["FIRE", "WATER"],
    fainted: false,
    poisoned: false,
    inCombat: false,
    paralyzed: false,
    burned: false,
    frozen: 0,
    confused: 0,
    asleep: 0,
    hp: 323,
    totalHP: 323,
    level: "Lv:100",
    combatLvl: 100,
    attack: 334,
    specialAttack: 212,
    defense: 226,
    specialDefense: 236,
    speed: 196,
    moves: [{
        name: "DRAGON RUSH",
        type: "DRAGON",
        physical: false,
        special: true,
        status: false,
        pp: 15,
        maxPP: 15,
        power: 100,
        accuracy: 1
    },
    {
        name: "TWISTER",
        type: "DRAGON",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        maxPP: 20,
        power: 65,
        accuracy: 1,
    },
    {
        name: "DRAGON BREATH",
        type: "DRAGON",
        physical: false,
        special: true,
        status: false,
        pp: 20,
        maxPP: 20,
        power: 60,
        accuracy: 1,
    },
    {
        name: "OUTRAGE",
        type: "DRAGON",
        physical: false,
        special: true,
        status: true,
        loseTurn: false,
        pp: 10,
        maxPP: 10,
        power: 120,
        accuracy: 1,
    }]
}]